### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by sheim** [burcutepekule/TimeDelayEmbedding#1]
Hi, I found this repo through your blog post, nicely written and very interesting!
I played around with your matlab implementation, in particular TAKENS02, to get some better intuition, and thought I'd point out a few things. I'd be curious on your thoughts.

First of all, you have 4 different systems, but always use the same parameters. This always seems to work reasonably well, but did you actually use different parameters and just upload one set?

More importantly, I tried changing the embedding dimension, including to 1, which should break the predictions but doesn't! I think this is because the default prediction time `T=1` is so small, that just predicting something else that is close is sufficient to keep the error small. Increasing `T` to higher values (e.g. 10 for the Lorenz system) indeed seems to highlight the importance of getting a proper embedding.

**Comment by burcutepekule** [comment]
Hi! Thanks a lot for the nice comments!

Yes, the parameters are the same for all systems, but you might need to fine tune the system given your data. Both examples are nicely periodic in these examples, but the optimal embedding delay will depend on the autocorrelation (or mutual information) of your signal - this can even be adaptive with a sliding window as you receive more data points in the future (thinking of a possible application for finance prediction purposes, for example).

I think regarding T=1, you are absolutely right. Most of the time to my experience, anything T>5 starts to be very very unreliable. That is also a good way to interpret what a "chaotic" system means from another perspective, that we cannot really see much ahead!

I hope my answers make sense :) cheers!

**Comment by sheim** [comment]
Yup, thanks!
